language: python
python:
    - "3.4"
    - "3.5"
install: 
    - pip install -U pip
    - pip install -U setuptools
    - pip install -r requirements.txt
    - pip install -r dev-requirements.txt
script: 
    - ./tests/flake.sh
    - coverage run --source=app -m pytest
after_success:
    - bash <(curl -s https://codecov.io/bash)

