language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
install: 
    - "pip install -r requirements.txt"
    - "pip install -r dev-requirements.txt"
    - "pip install coveralls"
script: 
    - ./tests/flake.sh
    - coverage run --source=app -m pytest
after_success:
    coveralls

